/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/ui/AppIcon.vue')['default']
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ChatView: typeof import('./components/ChatView.vue')['default']
    ContextTrimmed: typeof import('./components/ContextTrimmed.vue')['default']
    LoadingSpinner: typeof import('./components/ui/LoadingSpinner.vue')['default']
    MessageItem: typeof import('./components/MessageItem.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchStatus: typeof import('./components/SearchStatus.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SplashScreen: typeof import('./components/ui/SplashScreen.vue')['default']
    ThinkBlock: typeof import('./components/ThinkBlock.vue')['default']
  }
}
