/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSettings: typeof import('./components/settings/AboutSettings.vue')['default']
    AdvancedExperimentalSettings: typeof import('./components/settings/AdvancedExperimentalSettings.vue')['default']
    AIChatSettings: typeof import('./components/settings/AIChatSettings.vue')['default']
    APIServiceSettings: typeof import('./components/settings/APIServiceSettings.vue')['default']
    AppearanceSettings: typeof import('./components/settings/AppearanceSettings.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppIcon: typeof import('./components/ui/AppIcon.vue')['default']
    AttachmentPreview: typeof import('./components/AttachmentPreview.vue')['default']
    BackendManager: typeof import('./components/settings/BackendManager.vue')['default']
    ChatBehaviorSettings: typeof import('./components/settings/ChatBehaviorSettings.vue')['default']
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ChatToolbar: typeof import('./components/ChatToolbar.vue')['default']
    ContextTrimmed: typeof import('./components/ContextTrimmed.vue')['default']
    ExitOverlay: typeof import('./components/ExitOverlay.vue')['default']
    GpuAccelerationSettings: typeof import('./components/settings/GpuAccelerationSettings.vue')['default']
    HelpTip: typeof import('./components/ui/HelpTip.vue')['default']
    KvCacheSettings: typeof import('./components/settings/KvCacheSettings.vue')['default']
    LoraManager: typeof import('./components/LoraManager.vue')['default']
    MCPSettings: typeof import('./components/settings/MCPSettings.vue')['default']
    MessageItem: typeof import('./components/MessageItem.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    ModelSwitchOverlay: typeof import('./components/ModelSwitchOverlay.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDivider: typeof import('naive-ui')['NDivider']
    NetworkSettings: typeof import('./components/settings/NetworkSettings.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NIcon: typeof import('naive-ui')['NIcon']
    NText: typeof import('naive-ui')['NText']
    PerformanceModeSelector: typeof import('./components/settings/PerformanceModeSelector.vue')['default']
    PerformanceSettings: typeof import('./components/settings/PerformanceSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchStatus: typeof import('./components/SearchStatus.vue')['default']
    ServerConsole: typeof import('./components/ServerConsole.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SpeculativeDecodingSettings: typeof import('./components/settings/SpeculativeDecodingSettings.vue')['default']
    SplashScreen: typeof import('./components/ui/SplashScreen.vue')['default']
    TerminalConsole: typeof import('./components/TerminalConsole.vue')['default']
    ThinkBlock: typeof import('./components/ThinkBlock.vue')['default']
    TokenCounter: typeof import('./components/TokenCounter.vue')['default']
    TTSSettings: typeof import('./components/settings/TTSSettings.vue')['default']
    WebSearchSettings: typeof import('./components/settings/WebSearchSettings.vue')['default']
  }
}
