// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConversation() {
  return window['go']['main']['App']['CreateConversation']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function ExportConversation(arg1, arg2) {
  return window['go']['main']['App']['ExportConversation'](arg1, arg2);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCleanupResult() {
  return window['go']['main']['App']['GetCleanupResult']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetModelArchitecture() {
  return window['go']['main']['App']['GetModelArchitecture']();
}

export function GetModelCapabilities() {
  return window['go']['main']['App']['GetModelCapabilities']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function PrepareShutdown() {
  return window['go']['main']['App']['PrepareShutdown']();
}

export function RegenerateMessage(arg1, arg2) {
  return window['go']['main']['App']['RegenerateMessage'](arg1, arg2);
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function SearchMessages(arg1) {
  return window['go']['main']['App']['SearchMessages'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function StopGeneration() {
  return window['go']['main']['App']['StopGeneration']();
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
