// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';
import {chat} from '../models';
import {main} from '../models';
import {config} from '../models';
import {rag} from '../models';

export function AnthropicCountTokens(arg1:string):Promise<string>;

export function AnthropicMessages(arg1:string):Promise<string>;

export function ApplyTemplate(arg1:Array<llm.ChatMessage>):Promise<string>;

export function BuiltInTools(arg1:string):Promise<string>;

export function ClearModelParams(arg1:string):Promise<void>;

export function CompressConversation(arg1:string):Promise<chat.CompressResult>;

export function ConfirmStartupError():Promise<void>;

export function CountTokens(arg1:Array<llm.ChatMessage>):Promise<number>;

export function CreateConversation():Promise<chat.Conversation>;

export function CreateKnowledgeBase(arg1:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteDocument(arg1:string,arg2:string):Promise<void>;

export function DeleteKnowledgeBase(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DownloadBackend(arg1:string):Promise<void>;

export function DownloadHubModel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string):Promise<void>;

export function EraseSlot(arg1:number):Promise<void>;

export function ExportConversation(arg1:string,arg2:string):Promise<string>;

export function ExportConversationWithDialog(arg1:string,arg2:string):Promise<boolean>;

export function GenerateServerAPIKey():Promise<string>;

export function GetActiveKnowledgeBase():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetAvailableModels():Promise<Array<llm.ModelOption>>;

export function GetBackendStatus():Promise<main.BackendStatus>;

export function GetCleanupResult():Promise<Array<chat.AbnormalConversation>>;

export function GetConfig():Promise<config.Config>;

export function GetConversations():Promise<Array<chat.Conversation>>;

export function GetLastPromptTokens():Promise<number>;

export function GetLogLevel():Promise<string>;

export function GetLoraAdapters():Promise<Array<llm.LoraAdapter>>;

export function GetMCPServers():Promise<Array<config.MCPServerConfig>>;

export function GetMCPStatus():Promise<Record<string, config.MCPServerStatus>>;

export function GetMessages(arg1:string):Promise<Array<chat.Message>>;

export function GetMetrics():Promise<llm.MetricsSummary>;

export function GetModelCapabilities():Promise<llm.ModelCapabilities>;

export function GetModelDetails(arg1:string):Promise<llm.ModelDetails>;

export function GetModelParams(arg1:string):Promise<chat.ModelParams>;

export function GetSearchAPIKeys():Promise<main.SearchAPIKeys>;

export function GetServerLogs():Promise<string>;

export function GetServerStatus():Promise<llm.ServerStatus>;

export function GetSlots():Promise<Array<llm.SlotInfo>>;

export function GetStartupError():Promise<main.StartupError>;

export function GetTerminalHistory():Promise<string>;

export function GracefulExit():Promise<void>;

export function HandleCloseRequest():Promise<string>;

export function HasModelParams(arg1:string):Promise<boolean>;

export function HasServerAPIKey():Promise<boolean>;

export function Health():Promise<main.HealthStatus>;

export function IsConPTYMode():Promise<boolean>;

export function IsRAGEnabled():Promise<boolean>;

export function ListDocuments(arg1:string):Promise<Array<rag.DocumentMeta>>;

export function ListHubModelFiles(arg1:string,arg2:string):Promise<Array<llm.HubFile>>;

export function ListKnowledgeBases():Promise<Array<rag.CollectionInfo>>;

export function ListMCPTools():Promise<Array<config.MCPToolInfo>>;

export function PrepareShutdown():Promise<void>;

export function RefreshMcpTools():Promise<void>;

export function RegenerateMessage(arg1:string,arg2:string):Promise<void>;

export function ReloadModels():Promise<void>;

export function RenameConversation(arg1:string,arg2:string):Promise<void>;

export function ReportProblem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RerankEnabled():Promise<boolean>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function ResolveToolApproval(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function RestartApp():Promise<void>;

export function RestoreSlot(arg1:string):Promise<void>;

export function SaveMCPServers(arg1:Array<config.MCPServerConfig>):Promise<void>;

export function SaveModelParams(arg1:string):Promise<void>;

export function SaveSlot(arg1:string):Promise<void>;

export function SearchHubModels(arg1:string,arg2:string,arg3:number):Promise<Array<llm.HubModel>>;

export function SearchMessages(arg1:string):Promise<Array<chat.Message>>;

export function SelectImageFile():Promise<string>;

export function SelectLoraFile():Promise<string>;

export function SendMessage(arg1:chat.SendMessageParams):Promise<void>;

export function SetActiveKnowledgeBase(arg1:string):Promise<void>;

export function SetCloseAction(arg1:string):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function SetLoraAdapters(arg1:Array<llm.LoraAdapter>):Promise<void>;

export function SetRAGEnabled(arg1:boolean):Promise<void>;

export function SetSearchAPIKeys(arg1:main.SearchAPIKeys):Promise<void>;

export function ShowWindow():Promise<void>;

export function StopGeneration():Promise<void>;

export function StopThinking():Promise<void>;

export function SwitchBackend(arg1:string):Promise<void>;

export function SwitchModel(arg1:string):Promise<main.SwitchResult>;

export function SynthesizeSpeech(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<Array<number>>;

export function TestMCPConnection(arg1:config.MCPServerConfig):Promise<config.MCPConnectResult>;

export function Tokenize(arg1:string):Promise<Array<number>>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UploadDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
