// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConversation() {
  return window['go']['main']['App']['CreateConversation']();
}

export function CreateKnowledgeBase(arg1) {
  return window['go']['main']['App']['CreateKnowledgeBase'](arg1);
}

export function CountTokens(arg1) {
  return window['go']['main']['App']['CountTokens'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteDocument(arg1, arg2) {
  return window['go']['main']['App']['DeleteDocument'](arg1, arg2);
}

export function DeleteKnowledgeBase(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeBase'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function CompressConversation(arg1) {
  return window['go']['main']['App']['CompressConversation'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function ExportConversation(arg1, arg2) {
  return window['go']['main']['App']['ExportConversation'](arg1, arg2);
}

export function ExportConversationWithDialog(arg1, arg2) {
  return window['go']['main']['App']['ExportConversationWithDialog'](arg1, arg2);
}

export function GetActiveKnowledgeBase() {
  return window['go']['main']['App']['GetActiveKnowledgeBase']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCleanupResult() {
  return window['go']['main']['App']['GetCleanupResult']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetLoraAdapters() {
  return window['go']['main']['App']['GetLoraAdapters']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetModelCapabilities() {
  return window['go']['main']['App']['GetModelCapabilities']();
}

export function GetServerLogs() {
  return window['go']['main']['App']['GetServerLogs']();
}

export function GetTerminalHistory() {
  return window['go']['main']['App']['GetTerminalHistory']();
}

export function IsConPTYMode() {
  return window['go']['main']['App']['IsConPTYMode']();
}

export function ResizeTerminal(cols, rows) {
  return window['go']['main']['App']['ResizeTerminal'](cols, rows);
}

export function GetSlots() {
  return window['go']['main']['App']['GetSlots']();
}

export function GetSmartParams() {
  return window['go']['main']['App']['GetSmartParams']();
}

export function GetSearchAPIKeys() {
  return window['go']['main']['App']['GetSearchAPIKeys']();
}

export function HandleCloseRequest() {
  return window['go']['main']['App']['HandleCloseRequest']();
}

export function HasServerAPIKey() {
  return window['go']['main']['App']['HasServerAPIKey']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GracefulExit() {
  return window['go']['main']['App']['GracefulExit']();
}

export function IsRAGEnabled() {
  return window['go']['main']['App']['IsRAGEnabled']();
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function ListKnowledgeBases() {
  return window['go']['main']['App']['ListKnowledgeBases']();
}

export function PrepareShutdown() {
  return window['go']['main']['App']['PrepareShutdown']();
}

export function RegenerateMessage(arg1, arg2) {
  return window['go']['main']['App']['RegenerateMessage'](arg1, arg2);
}

export function ReloadModels() {
  return window['go']['main']['App']['ReloadModels']();
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function RerankEnabled() {
  return window['go']['main']['App']['RerankEnabled']();
}

export function RestoreSlot(arg1) {
  return window['go']['main']['App']['RestoreSlot'](arg1);
}

export function EraseSlot(arg1) {
  return window['go']['main']['App']['EraseSlot'](arg1);
}

export function SaveSlot(arg1) {
  return window['go']['main']['App']['SaveSlot'](arg1);
}

export function SearchMessages(arg1) {
  return window['go']['main']['App']['SearchMessages'](arg1);
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SelectLoraFile() {
  return window['go']['main']['App']['SelectLoraFile']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetActiveKnowledgeBase(arg1) {
  return window['go']['main']['App']['SetActiveKnowledgeBase'](arg1);
}

export function SetCloseAction(arg1) {
  return window['go']['main']['App']['SetCloseAction'](arg1);
}

export function SetLoraAdapters(arg1) {
  return window['go']['main']['App']['SetLoraAdapters'](arg1);
}

export function SetRAGEnabled(arg1) {
  return window['go']['main']['App']['SetRAGEnabled'](arg1);
}

export function SetSearchAPIKeys(arg1) {
  return window['go']['main']['App']['SetSearchAPIKeys'](arg1);
}

export function SetServerAPIKey(arg1) {
  return window['go']['main']['App']['SetServerAPIKey'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StopGeneration() {
  return window['go']['main']['App']['StopGeneration']();
}

export function StopThinking() {
  return window['go']['main']['App']['StopThinking']();
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function Tokenize(arg1) {
  return window['go']['main']['App']['Tokenize'](arg1);
}

export function GetLastPromptTokens() {
  return window['go']['main']['App']['GetLastPromptTokens']();
}

export function ApplyTemplate(arg1) {
  return window['go']['main']['App']['ApplyTemplate'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UploadDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadDocument'](arg1, arg2, arg3, arg4);
}
