// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConversation() {
  return window['go']['main']['App']['CreateConversation']();
}

export function CreateKnowledgeBase(arg1) {
  return window['go']['main']['App']['CreateKnowledgeBase'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteDocument(arg1, arg2) {
  return window['go']['main']['App']['DeleteDocument'](arg1, arg2);
}

export function DeleteKnowledgeBase(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeBase'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function ExportConversation(arg1, arg2) {
  return window['go']['main']['App']['ExportConversation'](arg1, arg2);
}

export function GetActiveKnowledgeBase() {
  return window['go']['main']['App']['GetActiveKnowledgeBase']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCleanupResult() {
  return window['go']['main']['App']['GetCleanupResult']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetModelCapabilities() {
  return window['go']['main']['App']['GetModelCapabilities']();
}

export function GetSearchAPIKeys() {
  return window['go']['main']['App']['GetSearchAPIKeys']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GracefulExit() {
  return window['go']['main']['App']['GracefulExit']();
}

export function IsRAGEnabled() {
  return window['go']['main']['App']['IsRAGEnabled']();
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function ListKnowledgeBases() {
  return window['go']['main']['App']['ListKnowledgeBases']();
}

export function PrepareShutdown() {
  return window['go']['main']['App']['PrepareShutdown']();
}

export function RegenerateMessage(arg1, arg2) {
  return window['go']['main']['App']['RegenerateMessage'](arg1, arg2);
}

export function ReloadModels() {
  return window['go']['main']['App']['ReloadModels']();
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function SearchMessages(arg1) {
  return window['go']['main']['App']['SearchMessages'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetActiveKnowledgeBase(arg1) {
  return window['go']['main']['App']['SetActiveKnowledgeBase'](arg1);
}

export function SetRAGEnabled(arg1) {
  return window['go']['main']['App']['SetRAGEnabled'](arg1);
}

export function SetSearchAPIKeys(arg1) {
  return window['go']['main']['App']['SetSearchAPIKeys'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StopGeneration() {
  return window['go']['main']['App']['StopGeneration']();
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UploadDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadDocument'](arg1, arg2, arg3, arg4);
}
